# Generated by Django 4.0.6 on 2022-07-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
