# Generated by Django 4.0.6 on 2022-07-21 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_remove_produto_data_produto_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ('descricao',)},
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='produto',
            new_name='descricao',
        ),
    ]
