# Generated by Django 4.0.6 on 2022-07-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('AP', 'Aprovado'), ('CA', 'Cancelado'), ('PE', 'Pendente'), ('EM', 'Em Análise')], default='EM', max_length=2),
        ),
    ]
