# Generated by Django 4.0.6 on 2022-07-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_data_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='item',
            new_name='produto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='pedido',
            name='Valor_total',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=7, verbose_name='preço'),
            preserve_default=False,
        ),
    ]
