# Generated by Django 4.0.6 on 2022-07-20 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_rename_item_pedido_produto_remove_pedido_quantidade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='Valor_total',
            new_name='valor_total',
        ),
    ]
