# Generated by Django 4.0.6 on 2022-07-20 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_ativo'),
        ('clientes', '0001_initial'),
        ('pedidos', '0007_rename_valor_total_pedido_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateTimeField(verbose_name='Data do Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='observacao',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='produto',
            field=models.ManyToManyField(to='produtos.produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('AP', 'Aprovado'), ('CA', 'Cancelado'), ('PE', 'Pendente'), ('EM', 'Em Análise')], default='EM', max_length=2, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor Total (R$)'),
        ),
    ]
